name: dnsdist-acme Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push the Docker image
      #   run: ./scripts/build.sh
      #   working-directory: ./

      - uses: depot/setup-action@v1

      - uses: depot/build-push-action@v1
        with:
          project: 83rwjkn7g4
          context: .
          push: true
          tags: ragibkl/dnsdist-acme:latest
